
const defaultFilters = [
	"*://partner.googleadservices.com/*",
	"*://*.googlesyndication.com/*",
	"*://*.google-analytics.com/*",
	"*://creative.ak.fbcdn.net/*",
	"*://*.adbrite.com/*",
	"*://*.exponential.com/*",
	"*://*.quantserve.com/*",
	"*://*.scorecardresearch.com/*",
	"*://*.zedo.com/*",
	"*://*.fullxxxvideos.net/wwwxxx/fullhdporn/*",
	"*://*.www.tubexclips.com/*",
	"*://*.m.fuq.com/*",
	"*://*.www.superhqporn.com/*",
	"*://*.m.perfectgirls.net/*",
	"*://*.mobile.youporn.com/*",
	"*://*.sexmob9.com/*",
	"*://*.hotgirlsex.net/*",
	"*://*.www.indianpornvideos.com/*",
	"*://*.xxxworld.in/*",
	"*://*.jugaadi.info/*",
	"*://*.savitabhabhi.mobi/*",
	"*://*.9maza.com/*",
	"*://*.xxxfuck.mobi/*",
	"*://*.sexmasti.info/*",
	"*://*.wapdesi.in/*",
	"*://*.erohot.net/*",
	"*://*.video.xnxx.com/*",
	"*://*.desixxx.mobi/*",
	"*://*.xporn.fiz.su/*",
	"*://*.desiindian.net/*",
	"*://*.sexnine.net/*",
	"*://*.xdesi.mobi/*",
	"*://*.www.gastimaza.com/*",
	"*://*.m.pornoid.com/*",
	"*://*.www.pornhdhub.xxx/*",
	"*://*.www.sextubehd.xxx/*",
	"*://*.desisexmovies.net/*",
	"*://*.desisexclips.com/*",
	"*://*.mobifcuk.com/*",
	"*://*.4tube.com /*",
	"*://*.8teenxxx.com/*",
	"*://*.Alotporn.com /*",
	"*://*.Beeg.com /*",
	"*://*.Bustnow.com/*",
	"*://*.Cliphunter.com /*",
	"*://*.Definebabes.com/*",
	"*://*.Deviantclip.com /*",
	"*://*.Drtuber.com/*",
	"*://*.Empflix.com /*",
	"*://*.www.Fantasti.cc /*",
	"*://*.Fapdu.com /*",
	"*://*.Freeporn.com /*",
	"*://*.Freudbox.com /*",
	"*://*.Fuq.com /*",
	"*://*.Fux.com /*",
	"*://*.Grayvee.com /*",
	"*://*.Hellxx.com /*",
	"*://*.Hustlertube.com /*",
	"*://*.Jugy.com /*",
	"*://*.Jizzhut.com /*",
	"*://*.Kaktuz.com /*",
	"*://*.Keezmovies.com /*",
	"*://*.Kinxxx.com /*",
	"*://*.Laraporn.com /*",
	"*://*.Leakedporn.com /*",
	"*://*.Lovelyclips.com /*",
	"*://*.Lubetube.com/*",
	"*://*.Mofosex.com /*",
	"*://*.Monstertube.com /*",
	"*://*.Madthumbs.com /*",
	"*://*.Moviefap.com /*",
	"*://*.Moviesand.com /*",
	"*://*.Orgasm.com /*",
	"*://*.Perfectgirls.net /*",
	"*://*.Pichunter.com /*",
	"*://*.Planetsuzy.com /*",
	"*://*.Porn.com /*",
	"*://*.Porn-plus.com /*",
	"*://*.Porncor.com /*",
	"*://*.Pornhub.com /*",
	"*://*.Pornrabbit.com /*",
	"*://*.Porntitan.com /*",
	"*://*.Pussy.org /*",
	"*://*.Redtube.com /*",
	"*://*.Tube8.com /*",
	"*://*.Xhamster.com/*",
	"*://*.Xnxx.com /*",
	"*://*.Xvideos.com /*",
	"*://*.Youjizz.com /*",
	"*://*.www.4tube.com/*",
	"*://*.www.8teenxxx.com/*",
	"*://*.www.alotporn.com/*",
	"*://*.www.beeg.com/*",
	"*://*.www.bustnow.com/*",
	"*://*.www.cliphunter.com/*",
	"*://*.www.definebabes.com/*",
	"*://*.www.deviantclip.com/*",
	"*://*.www.drtuber.com/*",
	"*://*.www.empflix.com/*",
	"*://*.www.fantasti.cc/*",
	"*://*.www.fapdu.com/*",
	"*://*.www.freeporn.com/*",
	"*://*.www.freudbox.com/*",
	"*://*.www.fuq.com/*",
	"*://*.www.fux.com/*",
	"*://*.www.grayvee.com/*",
	"*://*.www.hellxx.com/*",
	"*://*.www.hustlertube.com/*",
	"*://*.www.jugy.com/*",
	"*://*.www.jizzhut.com/*",
	"*://*.www.kaktuz.com/*",
	"*://*.www.keezmovies.com/*",
	"*://*.www.kinxxx.com/*",
	"*://*.www.laraporn.com/*",
	"*://*.www.leakedporn.com/*",
	"*://*.www.lovelyclips.com/*",
	"*://*.www.lubetube.com/*",
	"*://*.www.mofosex.com/*",
	"*://*.www.monstertube.com/*",
	"*://*.www.madthumbs.com/*",
	"*://*.www.moviefap.com/*",
	"*://*.www.moviesand.com/*",
	"*://*.www.orgasm.com/*",
	"*://*.www.perfectgirls.net/*",
	"*://*.www.pichunter.com/*",
	"*://*.www.planetsuzy.com/*",
	"*://*.www.porn.com/*",
	"*://*.www.porn-plus.com/*",
	"*://*.www.porncor.com/*",
	"*://*.www.pornhub.com/*",
	"*://*.www.pornrabbit.com/*",
	"*://*.www.porntitan.com/*",
	"*://*.www.pussy.org/*",
	"*://*.www.redtube.com/*",
	"*://*.www.tube8.com/*",
	"*://*.www.xhamster.com/*",
	"*://*.www.xnxx.com/*",
	"*://*.www.xvideos.com/*",
	"*://*.www.youjizz.com/*",
	"*://*.www.ladies20.com/*",
	"*://*.cheatswifexxx.com/*"

]
let date = new Date();
let hours = date.getHours();
defaultFilters1 = ["*://*.facebook.com/*", "*://*.twitter.com/*", "*://*.instagram.com/*"];
if (hours >= 10 && hours < 22) {
	console.log('Time to block websites');
	chrome.webRequest.onBeforeRequest.addListener(
		function (details) { return { cancel: true } },
		{ urls: defaultFilters1 },
		["blocking"]
	)
}
else {
	console.log('Time to unblock websites');
}

chrome.webRequest.onBeforeRequest.addListener(
	function (details) { return { cancel: true } },
	{ urls: defaultFilters },
	["blocking"]
)
